[project]
name = "openaiaudio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.2.6",
    "openai>=1.79.0",
    "sounddevice>=0.5.2",
]
